import React from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Shield, Zap, Sparkles, FileText, Cpu, Lock, TrendingUp, Target, ArrowRight } from 'lucide-react';
import SEO from '../components/SEO';

const Features = () => {
  const navigate = useNavigate();
  
  const features = [
    {
      icon: <Shield className="h-8 w-8" />,
      title: 'AI Detection',
      desc: 'Our advanced AI can detect content generated by ChatGPT, Claude, Gemini, and other AI models with 98.4% accuracy.',
      color: 'blue'
    },
    {
      icon: <Sparkles className="h-8 w-8" />,
      title: 'Text Humanizer',
      desc: 'Transform AI-generated text into natural, human-like content that bypasses AI detectors.',
      color: 'purple'
    },
    {
      icon: <FileText className="h-8 w-8" />,
      title: 'Plagiarism Check',
      desc: 'Check your content against billions of web pages and academic papers to ensure originality.',
      color: 'green'
    },
    {
      icon: <Cpu className="h-8 w-8" />,
      title: 'Gemini Powered',
      desc: 'Built on Google\'s Gemini 1.5 Pro for state-of-the-art natural language understanding.',
      color: 'orange'
    },
    {
      icon: <Lock className="h-8 w-8" />,
      title: 'Privacy First',
      desc: 'Your content is never stored or used for training. Complete privacy guaranteed.',
      color: 'pink'
    },
    {
      icon: <TrendingUp className="h-8 w-8" />,
      title: 'Detailed Reports',
      desc: 'Get sentence-by-sentence analysis with perplexity scores and improvement suggestions.',
      color: 'cyan'
    },
    {
      icon: <Zap className="h-8 w-8" />,
      title: 'Instant Results',
      desc: 'Get analysis results in under 3 seconds, even for long-form content.',
      color: 'yellow'
    },
    {
      icon: <Target className="h-8 w-8" />,
      title: 'Smart Highlighting',
      desc: 'Visual color-coded highlights show exactly which parts need attention.',
      color: 'red'
    },
  ];

  return (
    <div className="min-h-screen pt-24 px-4 pb-16">
      <SEO 
        title="Features - Advanced Plagiarism & AI Detection"
        description="Discover PlagZap's key features, including deep search plagiarism check, grammar analysis, AI content detector, and content humanization."
        canonical="/features"
        keywords="plagzap features, plagiarism scanner, grammar helper, ai detection"
      />
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-16"
        >
          <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 bg-clip-text text-transparent">
            Powerful Features
          </h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Everything you need to ensure your content is original, authentic, and human.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 * idx }}
              className="bg-background/50 border border-white/10 rounded-2xl p-6 hover:border-purple-500/30 hover:scale-105 transition-all duration-300"
            >
              <div className="inline-flex p-3 rounded-xl bg-purple-500/20 text-purple-400 mb-4">
                {feature.icon}
              </div>
              <h3 className="text-lg font-bold text-white mb-2">{feature.title}</h3>
              <p className="text-gray-400 text-sm leading-relaxed">{feature.desc}</p>
            </motion.div>
          ))}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="mt-16 text-center"
        >
          <button
            onClick={() => navigate('/analyzer')}
            className="px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-bold rounded-xl text-lg transition-all flex items-center gap-2 mx-auto"
          >
            Try It Now <ArrowRight className="h-5 w-5" />
          </button>
        </motion.div>
      </div>
    </div>
  );
};

export default Features;
